### ISSUE TITLE
New release with fixes for Python >=3.5 off master?

### ISSUE THREAD

**Issue by hartwork** [schettino72/mergedict#3]
Hi!

It seems that commit c3f6333298c86e5681af282c7210eb1047a991dd never went into a Git tag or a release on PyPI. Could that be fixed to unbreak support for Python >=3.4?

Thanks and best, Sebastian

**Comment by schettino72** [comment]
Hi @hartwork , I have just added you as a collaborator in github. Let me know you pypi handle and I will also add you as an admin so you can make a release yourself (in case you are interested).

**Comment by hartwork** [comment]
Okay cool!

I'm https://pypi.org/user/sping/ up there.

**Comment by schettino72** [comment]
ok. added you. Welcome :smile: 

Please add yourself to "authors" list. and update CHANGES file when making a release.

**Comment by hartwork** [comment]
> ok. added you. Welcome smile

Thank you!

> Please add yourself to "authors" list. and update CHANGES file when making a release.

Added myself at 549f7b5bc8f894f506e32f01235d30b85bd2a213 now. Extended the `CHANGES` log a bit already, will keep it in mind. If you can think of something missing in the, please let me know.

**Comment by hartwork** [comment]
Fixed by #8, closing.

https://pypi.org/project/mergedict/#history
