### ISSUE TITLE
Circular dependency with configclass, doit and doit-py

### ISSUE THREAD

**Issue by dvzrv** [schettino72/mergedict#9]
Hi! Similar to what was discussed in https://github.com/schettino72/configclass/issues/4 having doit and doit-py as test dependencies for mergedict means an even more complicated bootstrap for doit and doit-py.

Is it not possible to test mergedict without doit and doit-py?

**Comment by hartwork** [comment]
I think my reply at https://github.com/schettino72/configclass/issues/4#issuecomment-685888639 applies to mergedict as well. Maybe let's figure things out for configclass first and then we come back here.

**Comment by dvzrv** [comment]
I actually need mergedict before I can package configclass :)

**Comment by dvzrv** [comment]
Alright, false alarm: Running pytest against the build works just fine. doit and doit-py are not required!
